### ISSUE TITLE
IOS Patcher - Windows XP Crash

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24/IOS-Patcher#12]
User reported bug.
* IOS Patcher crashing on Windows XP.

 Working on fixing it. Any help would be appreciated.

**Comment by 466gaming** [comment]
On Discord, DM RiiConnect24 Bot `!wads` for pre-patched IOS31 and IOS80 wads.

**Comment by KcrPL** [comment]
Thanks for help. Really. You helped me a lot.

**Comment by ghost** [comment]
Closing as wont-fix: 

Windows XP was released in 2001, newer tools do not support it. If you have an issue, update to 7.
RiiConnect24 does not take support requests for below Vista SP2.

**Comment by AggPro** [comment]
Crashes on Vista SP2 too

**Comment by KcrPL** [comment]
RiiConnect doesn't but i do ;)
I just wasn't home so i couldn't fix XP problem but if i will, i will fix it ASAP if it's possible.

And Vista... hmm. Are you using an option called: 
"C. [ ] If this program is crashing try selecting this option."?
If not - try it.

**Comment by ghost** [comment]
@KcrPL you'll find a lot of our tools may be the issue since they all use newer things only 7+ can use.
If you wish to go hellbent on fixing it for XP and Vista, go ahead, but there is _no_ point.
No support will be given from our end.

**Comment by KcrPL** [comment]
Hmm. That might be cause of crashes...
But if the tool would fail it should give exit code but it crashes.

![1234](https://user-images.githubusercontent.com/17184296/28500080-0b1ed832-6fc3-11e7-8a33-5417c85798f6.JPG)
![12345](https://user-images.githubusercontent.com/17184296/28500100-5107eb22-6fc3-11e7-899e-6377fceca729.JPG)

![qi1fpyu](https://user-images.githubusercontent.com/17184296/28500069-ba8934da-6fc2-11e7-9ec3-85b7b9ef2ea7.gif)

**Comment by KcrPL** [comment]
BTW,
@AggPro Try downloading the latest release of IOS Patcher and try to patch it again.

**Comment by spotlightishere** [comment]
Could you guys take this elsewhere, off GitHub? I find it somewhat absurd we're talking about supporting a pretty much unsupported OS, despite several others here asking to stop.

**Comment by KcrPL** [comment]
I don't think it's absurd - there are still many users that use Windows XP. Patcher is 100% compatible with Windows XP. It's just matter of the tools that it's using (Sharpii etc.)

**Comment by larsenv** [comment]
Well, less people are using Windows XP every day. Microsoft ended support for Windows XP, so why would we support it?

**Comment by KcrPL** [comment]
Wait wait wait, what are we even talking about? Right now i'm the only one who supports Windows version. So... every issue goes to me, not to you :O 

Hmm... But why would we support it? Because it's old it doesn't mean that we don't have to support it, right?
Anyway i think i already released update about <b>End of Support for Windows XP</b> so it doesn't matter.
![1](https://user-images.githubusercontent.com/17184296/28501788-9b86b910-6fe3-11e7-9f3a-233e2a4357a3.gif)

**Comment by spotlightishere** [comment]
You know that everyone in the RiiConnect24 organization is getting issue emails, right? We also have the ability to edit your responses. tread lightly.

Meanwhile... yes, thank you for displaying the message about it not being supported. We're donehere, then

**Comment by KcrPL** [comment]
"You know that everyone in the RiiConnect24 organization is getting issue emails, right?"

* Everyone but not me :P

"Meanwhile... yes, thank you for displaying the message about it not being supported."

* No problem xD

**Comment by ghost** [comment]
I'll leave the final comment:
RiiConnect24 is not going to support Windows XP. You are working on a project that bears RiiConnect24's name. As such, we are more than allowed to say _No XP support_.
Please do not make us rethink letting you collaborate with us. Thank you.

**Comment by spotlightishere** [comment]
No, I'll leave the final comment because #rebelrebel

he added in a thing that says XP isn't supported instead of adding support, so we're good. your last statement is true, though

**Comment by KcrPL** [comment]
Uhm... excactly.
![1](https://user-images.githubusercontent.com/17184296/28502464-54576a2a-6ff3-11e7-99b3-452cb8de1c10.JPG)

**Comment by larsenv** [comment]
That looks like it's on Windows 10... did you add the note correctly?

**Comment by KcrPL** [comment]
Yes, i only forced it to show it to make this screenshot.

> goto winxp_notice

**Comment by KcrPL** [comment]
Just wanted to say that now support for Windows XP is like 100% ended. Why? Recently we added auto update feature and XP doesn't support powershell so we are unable to even run IOS Patcher itself because it will show error about **Update server not available**.

**Comment by KcrPL** [comment]
Issue fixed. Code has been optimized for Windows XP - some features are disabled (like auto updating) but it's working. 👌
