### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by caden3ds** [RiiConnect24/IOS-Patcher#19]
When I open it says "Press any button to continue" So I pressed "a" and it crashed. I tried using other buttons but it still didn't work.

**Comment by KcrPL** [comment]
Hi @caden3ds, 

Can you please tell me what is your system version?

PS. It doesn't matter which key you will press.

**Comment by caden3ds** [comment]
What do you mean?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by KcrPL** [comment]
What is your Windows version? (example: Windows XP, Windows 7 x64, Windows 10 x32)

**Comment by GtgGhost** [comment]
I think I'm getting the same thing
Windows 10 Home Version 1709

> The system cannot find the path specified.
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request.

At line:1 char:1
+ (new-object System.Net.WebClient).DownloadFile('https://kcrpl.github. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At line:1 char:1
+ (new-object System.Net.WebClient).DownloadFile('https://kcrpl.github. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

The system cannot find the path specified.
set was unexpected at this time.

**Comment by KcrPL** [comment]
@GtgGhost Please create a new Issue about that.

**Comment by KcrPL** [comment]
@caden3ds: This issue has been fixed. Download it from [here](https://github.com/RiiConnect24/IOS-Patcher/releases)
