### ISSUE TITLE
Invalid package name

### ISSUE THREAD

**Issue by InternalLoss** [RiiConnect24/IOS-Patcher#22]
In the error message:
```
This is a patcher that creates an IOS31 and IOS80 WAD.
This is only for the Wii, please don't install this on a Wii U.
I'm missing xdelta3, please install with homebrew at https://brew.sh/
```
it's specifying `xdelta3`. However, `xdelta` is brew's name for it. 

Furthermore, a better sentence would be
```
use `brew install xdelta` to get this required package. If you do not have brew, get it at https://brew.sh```

**Comment by LexHDev** [comment]
```bash
  darwin*)
    hash mono 2>/dev/null || { echo >&2 "I'm missing mono, please install with the homebrew package manager at https://brew.sh/";exit 1;}
    hash xdelta3 2>/dev/null || { echo >&2 "I'm missing xdelta, please install with homebrew at https://brew.sh/"; exit 1; } ;;
```

It should be printing xdelta for the "I'm missing" message, are you sure you're using an up to date version?

**Comment by InternalLoss** [comment]
I was using the latest release from /releases

**Comment by LexHDev** [comment]
```bash
	darwin*)  
		hash mono 2>/dev/null || { echo >&2 "I'm missing mono, please install with the homebrew package manager at https://brew.sh/";exit 1;}
		hash xdelta3 2>/dev/null || { echo >&2 "I'm missing xdelta3, please install with homebrew at https://brew.sh/"; exit 1; };;
```
You seem to be right, after downloading the release it's certainly not the most recent one, does someone mind updating the release with the newer commits. @KcrPL 

You can modify the sentence quite easily as long as you don't modify anything out of the quotation marks btw PokeAcer.

**Comment by KcrPL** [comment]
Oops, i thought that somebody was updating Linux/Mac version.

**Comment by LexHDev** [comment]
@KcrPL tbh I should have, but I haven't had the time to, and didn't know about it until now, only responding to the git commits, and giving advice atm.

**Comment by LexHDev** [comment]
If you'd still like to update the brew.sh information, by all means.

**Comment by spotlightishere** [comment]
Lucky for PokeAcer, I had just wiped my Mac, so no packages.
```
spot at spotlights-imac in ~/Projects/Wii/IOS-Patcher/UNIX on master ✔    
> bash patch.sh
This is a patcher that creates an IOS31 and IOS80 WAD.
I'm missing mono, please install with the homebrew package manager at https://brew.sh/
spot at spotlights-imac in ~/Projects/Wii/IOS-Patcher/UNIX on master ✔
> brew install mono
[teleports package and installs]
spot at spotlights-imac in ~/Projects/Wii/IOS-Patcher/UNIX
> bash patch.sh
This is a patcher that creates an IOS31 and IOS80 WAD.
I'm missing xdelta, please install with homebrew at https://brew.sh/
```

I can't reproduce getting `xdelta3` to show. However, I agree that the sentence formatting should be changed, so here shortly I'll make a commit updating that. @pokeacer, what macOS version and etc were you on?

**Comment by spotlightishere** [comment]
Apologies, after reading, I finally understood that the UNIX release zip wasn't up to date. 😅 
I'll go update that after commit.
