### ISSUE TITLE
Windows installation and uninstallation issue

### ISSUE THREAD

**Issue by windowscustomer** [RiiConnect24/IOS-Patcher#23]
Windows is used by most of the people there are many problems faced by the users like crashing, uninstallation, installation for this issues you can contact to  [Windows Customer Service](https://babasupport.org/microsoft/windows-customer-service/150) where technical experts always available to help you.

**Comment by ArtutoGamer** [comment]
This is so fucking good.

**Comment by DismissedGuy** [comment]
Lool

**Comment by KcrPL** [comment]
Don't worry, my IOS Patcher has Customer Service built in, I'm watching you 24/7 :P

Lmao

**Comment by dhtdht020** [comment]
I luv it
